### ISSUE TITLE
Paycash onboarding

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-payment#1]
This `Payments` app will contain all UIs related to payments
- Look & feel can be based on https://docs.greenitglobe.com/rubenmattan/js-research/src/master/src/payments
- Uses `cordova-rogerthat-payments-plugin` and maybe `cordova-rogerthat-plugin`
  - `cordova-rogerthat-payments-plugin` will use the ios/android PaymentPlugin (a plugin like FriendsPlugin) for
    - listing the user's accounts
    - listing transactions
    - signing up to a payment provider (can contain pp specific code)
    - ...
  - `cordova-rogerthat-payments-plugin` must be able to execute backlog calls
    - [ ] add typescript TO/api/capi generator
- If the user does not have any account with any payment provider
  - [ ] Show a screen explaining how the user can create an account with a payment provider (UI like the empty service list).
  - [ ] This screen contain a big PLUS button to signup to a payment provider
    - [ ] In case of paycash we'll need to load the paycash user creation page
- If the user is has an account with any payment provider
  - [ ] Show a list of accounts, grouped by payment providers
  - [ ] Show a plus button in the navigation bar, to create a new account with a payment provider

**Comment by lucasvanhalst** [comment]
Onboarding for paycash: go to https://sandbox.paycash.eu/authorization-server/oauth/authorize?response_type=code&client_id=mobicage

**Comment by lucasvanhalst** [comment]
1) open payment activity
2) check db for payment providers.
3) Show list providers
4) Login to provider (authorise url)
5) code -> rogerthat backend -> redirect to app
6) show ionic thing with account details
