### ISSUE TITLE
Set colours during build process via a config file

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-payment#12]
A config.json in the root of the repo should contain the following keys (remove the 'colors' root key that's already in there now on the branch): primary_color, secondary_color, danger_color, light_color, dark_color

for each of these keys, find and replace occurrences of the keys in the code. But prefix/suffex them like this: <%= primary_color %>

Then, in the variables.scss file, replace 
```scss
$colors: (
  primary: #488aff,
  secondary: #32db64,
  danger: #f53d3d,
  light: #f4f4f4,
  dark: #222
);
```
with
```scss
$colors: (
  primary: <%= primary_color %>,
  secondary: <%= seconary_color %>,
  danger: <%= danger_color %>,
  light: <%= light_color %>,
  dark: <%= dark_color %>
);
```

Use branch https://github.com/rogerthat-platform/rogerthat-payment/tree/colours
Use this webpack plugin https://www.npmjs.com/package/string-replace-webpack-plugin

For testing, just run `ionic serve` and if it doesn't throw errors it's probably okay. Don't bother testing it for real as it is a bit complicated since it doesn't work in the browser, I'll do that instead when you're done

**Comment by abom** [comment]
After struggling with webpack to get it to replace custom strings with string-replace-webpack-plugin, it didn't work at the end, so @lucasvanhalst wrote a script to set only the colors before build.

**Comment by lucasvanhalst** [comment]
Happy with how it works now. build:prepare must be run before building, it accepts colors as command line arguments which in turn generates a colors.scss file.
