### ISSUE TITLE
I don't see my balance for my asset

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-payment#22]
```{"provider_id":"threefold","id":"***","type":"account","name":"Account: TFF","currency":"TFF","balance":1000,"verified":true,"enabled":true,"has_balance":true,"has_transactions":true,"required_action":null}```

**Comment by lucasvanhalst** [comment]
Made something but not really satisfied with the UI
![2017-08-23 17 20 16](https://user-images.githubusercontent.com/6652304/29623657-5e89913e-8827-11e7-9e52-a755529342b8.jpg)

**Comment by RubenMattan** [comment]
Remove the TFF below balance and align the amount + currency to the right

**Comment by RubenMattan** [comment]
It doesn't have enough space...

![screenshot_1503576990](https://user-images.githubusercontent.com/1122760/29666008-d4fd45b8-88d6-11e7-9d67-ef8fcd7c13b0.png)
